const drums = [
{ id: 1,
  name: 'EXOTIC MONOGRAM',
  brand: 'DW',
  size: '5x14',
  material: 'Maple' },
{ id: 2,
  name: 'CONCRETE',
  brand: 'DW',
  size: '5.5x14',
  material: 'Metal' },
{ id: 3,
  name: 'DW EDGE',
  brand: 'DW',
  size: '6x13',
  material: 'Maple' },
{ id: 4,
  name: 'Reference',
  brand: 'Pearl',
  size: '5x14',
  material: 'Metal' },
{ id: 5,
  name: 'Custom Classic',
  brand: 'Pearl',
  size: '5.5x14',
  material: 'Maple' },
{ id: 6,
  name: 'Joey Jordison',
  brand: 'Pearl',
  size: '6.5x13',
  material: 'Steel' },
{ id: 7,
  name: 'Ian Paice',
  brand: 'Pearl',
  size: '14x6.5',
  material: 'Steel' },
{ id: 8,
  name: 'D-515PA',
  brand: 'Sonar',
  size: '14x5.75',
  material: 'Rosewood' },
{ id: 9,
  name: 'SQ1-1465SDW',
  brand: 'Sonar',
  size: '14x6.5',
  material: 'Birch' },
{ id: 10,
  name: 'SDS1450JC',
  brand: 'Sakae',
  size: '14x5',
  material: 'Cypress' } 
];

const drum = {
  "name": "Free Floating",
  "brand": "Pearl",
  "size": "x14",
  "material": "Maple"
};

module.exports = {
  drum,
  drums
};